### ISSUE TITLE
从高级区升终极区的第一周，丢失深渊数据

### ISSUE THREAD

**Issue by chingkingm** [chingkingm/honkai_mys#33]
``` python
[2022-04-05 19:59:26,354 崩坏3角色卡片] ERROR: <class 'KeyError'> occured when bh3_player_card handling message -471036006.
[2022-04-05 19:59:26,355 崩坏3角色卡片] ERROR: 0
Traceback (most recent call last):
  File "C:\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\HoshinoBot\hoshino\modules\honkai_mys\__init__.py", line 83, in bh3_player_card
    im = await ind.draw_card(qid)
  File "C:\HoshinoBot\hoshino\modules\honkai_mys\modules\image_handle.py", line 486, in draw_card
    text=ItemTrans.abyss_level(self.index.stats.new_abyss.level),
  File "C:\HoshinoBot\hoshino\modules\honkai_mys\modules\util.py", line 144, in abyss_level
    return level[no]
KeyError: 0
```

**Comment by chingkingm** [comment]
具体表现为超弦空间没数据，量子奇点/量子流形查不了
