### ISSUE TITLE
更新最新后报错

### ISSUE THREAD

**Issue by doiss** [chingkingm/honkai_mys#37]
[2022-04-07 15:38:23,229 nonebot] INFO: Succeeded to import "hoshino.modules.mem_birthday.update_age"
[2022-04-07 15:38:23,286 nonebot] ERROR: Failed to import "hoshino.modules.honkai_mys.autosign", error: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1
[2022-04-07 15:38:23,287 nonebot] ERROR: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\__init__.py", line 7, in <module>
    from .modules.database import DB
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\database.py", line 7, in <module>
    from .mytyping import config
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\mytyping.py", line 31, in <module>
    config = Config(**Config.load_config())
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\mytyping.py", line 26, in load_config
    CONFIG = yaml.load(f, Loader=yaml.FullLoader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1
[2022-04-07 15:38:23,305 nonebot] ERROR: Failed to import "hoshino.modules.honkai_mys.guess_voice", error: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1
[2022-04-07 15:38:23,306 nonebot] ERROR: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\__init__.py", line 7, in <module>
    from .modules.database import DB
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\database.py", line 7, in <module>
    from .mytyping import config
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\mytyping.py", line 31, in <module>
    config = Config(**Config.load_config())
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\mytyping.py", line 26, in load_config
    CONFIG = yaml.load(f, Loader=yaml.FullLoader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 9, column 1
could not find expected ':'
  in "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\honkai_mys\modules\../config.yaml", line 10, column 1

**Comment by chingkingm** [comment]
`config.yaml`的格式似乎有问题，麻烦脱敏后发一下

**Comment by doiss** [comment]
![image](https://user-images.githubusercontent.com/97965580/162154935-051cce8a-da79-44e4-8f14-bcf1996fda15.png)

**Comment by chingkingm** [comment]
冒号`:`和内容之间要有空格，像这样
``` yaml
username: someone@qq.com
# QQ邮箱授权码
password: aaaaaaaaaaaaa
```

**Comment by doiss** [comment]
谢谢大佬，已经解决
