### ISSUE TITLE
请问大佬能适配个NoneBot2版本的吗

### ISSUE THREAD

**Issue by Kiana1314** [chingkingm/honkai_mys#39]

**Comment by chingkingm** [comment]
https://github.com/chingkingm/honkai_mys/tree/nonebot 切分支

**Comment by Kiana1314** [comment]
配置后启动使用指令无反应
06-24 16:14:08 [SUCCESS] nonebot | NoneBot is initializing...
06-24 16:14:08 [INFO] nonebot | Current Env: dev
06-24 16:14:08 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 6660, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep':
 {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev'}
06-24 16:14:09 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-24 16:14:09 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
06-24 16:14:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
06-24 16:14:11 [SUCCESS] nonebot | Succeeded to import "guess_voice"
06-24 16:14:11 [SUCCESS] nonebot | Succeeded to import "modules"
06-24 16:14:11 [SUCCESS] nonebot | Succeeded to import "autosign"
06-24 16:14:11 [SUCCESS] nonebot | Running NoneBot...
06-24 16:14:11 [DEBUG] nonebot | Loaded adapters: OneBot V11
06-24 16:14:11 [INFO] uvicorn | Will watch for changes in these directories: ['C:\\bot\\BH\\bh3']
2022-06-24 16:14:11 INFO Will watch for changes in these directories: ['C:\\bot\\BH\\bh3']
06-24 16:14:11 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:6660 (Press CTRL+C to quit)
2022-06-24 16:14:11 INFO Uvicorn running on http://127.0.0.1:6660 (Press CTRL+C to quit)
06-24 16:14:12 [INFO] uvicorn | Started reloader process [5064] using watchgod
2022-06-24 16:14:12 INFO Started reloader process [5064] using watchgod
06-24 16:14:12 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
06-24 16:14:13 [SUCCESS] nonebot | NoneBot is initializing...
06-24 16:14:13 [INFO] nonebot | Current Env: dev
06-24 16:14:13 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 6660, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep':
 {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
06-24 16:14:13 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-24 16:14:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
06-24 16:14:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
06-24 16:14:15 [SUCCESS] nonebot | Succeeded to import "guess_voice"
06-24 16:14:15 [SUCCESS] nonebot | Succeeded to import "modules"
06-24 16:14:15 [SUCCESS] nonebot | Succeeded to import "autosign"
06-24 16:14:15 [INFO] uvicorn | Started server process [2808]
2022-06-24 16:14:15 INFO Started server process [2808]
06-24 16:14:15 [INFO] uvicorn | Waiting for application startup.
2022-06-24 16:14:15 INFO Waiting for application startup.

**Comment by Kiana1314** [comment]
06-24 16:22:50 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: bh# (
-2111970982)
06-24 16:22:50 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message -2111970982 from 1832399834@[
群:950180960] "bh#"
06-24 16:22:50 [DEBUG] nonebot | Checking for matchers in priority 1...
06-24 16:22:50 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-24 16:22:56 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: bhv#
(477721849)
06-24 16:22:56 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message 477721849 from 1832399834@[群:
950180960] "bhv#"
06-24 16:22:56 [DEBUG] nonebot | Checking for matchers in priority 1...
06-24 16:22:56 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-24 16:23:01 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: bhf (
1803437167)
06-24 16:23:01 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message 1803437167 from 1832399834@[群
:950180960] "bhf"
06-24 16:23:01 [DEBUG] nonebot | Checking for matchers in priority 1...
06-24 16:23:01 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-24 16:23:06 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: 崩坏3
自动签到 (-227076651)
06-24 16:23:06 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message -227076651 from 1832399834@[群
:950180960] "崩坏3自动签到"
06-24 16:23:06 [DEBUG] nonebot | Checking for matchers in priority 1...
06-24 16:23:06 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-24 16:23:06 [INFO] nonebot | Event will be handled by <Matcher from honkai_mys.autosign, type=message, priority=1, te
mp=False>
06-24 16:23:06 [DEBUG] nonebot | Running matcher <Matcher from honkai_mys.autosign, type=message, priority=1, temp=False
>
06-24 16:23:06 [DEBUG] nonebot | Running handler <Dependent call=<function switch_autosign at 0x000000E280425430>, param
s=[ModelField(name='bot', type=Bot, required=True), ModelField(name='ev', type=Event, required=True), ModelField(name='m
atch', type=tuple, required=True)], parameterless=[]>
06-24 16:23:06 [INFO] nonebot | Matcher <Matcher from honkai_mys.autosign, type=message, priority=1, temp=False> running
 complete
06-24 16:23:06 [ERROR] nonebot | Running matcher <Matcher from honkai_mys.autosign, type=message, priority=1, temp=False
> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\bot\BH\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\honkai_mys\autosign\__init__.py", line 99, in switch_autosign
    hk3 = check_cookie(qid)
  File ".\honkai_mys\autosign\__init__.py", line 70, in check_cookie
    db = DB('uid.sqlite', tablename="qid_uid")
  File ".\honkai_mys\modules\database.py", line 28, in __init__
    super().__init__(
  File "C:\bot\BH\venv\lib\site-packages\sqlitedict.py", line 144, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, .\honkai_mys\modules\../.\honkai_mys\modules\.././data
06-24 16:23:06 [DEBUG] nonebot | Stop event propagation

**Comment by chingkingm** [comment]
输入指令没反应的话可能是因为nb2默认以‘/’为前缀，我这边测试可以正常触发。

后面发的这个报错没看太明白，可以发全一点.

**Comment by Kiana1314** [comment]
后台有触发指令了  但是会报错

PS C:\bot\BH> venv\scripts\activate
(venv) PS C:\bot\BH> cd bh3
(venv) PS C:\bot\BH\bh3> nb run
06-26 01:20:13 [SUCCESS] nonebot | NoneBot is initializing...
06-26 01:20:13 [INFO] nonebot | Current Env: dev
06-26 01:20:13 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 6660, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep':
 {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
06-26 01:20:13 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-26 01:20:13 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
06-26 01:20:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "guess_voice"
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "autosign"
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "modules"
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "tests"
06-26 01:20:16 [DEBUG] nonebot | Adapter "OneBot V11" already exists
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "echo"
06-26 01:20:16 [SUCCESS] nonebot | Succeeded to import "bot"
06-26 01:20:16 [SUCCESS] nonebot | Running NoneBot...
06-26 01:20:16 [DEBUG] nonebot | Loaded adapters: OneBot V11
06-26 01:20:16 [INFO] uvicorn | Will watch for changes in these directories: ['C:\\bot\\BH\\bh3']
2022-06-26 01:20:16 INFO Will watch for changes in these directories: ['C:\\bot\\BH\\bh3']
06-26 01:20:16 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:6660 (Press CTRL+C to quit)
2022-06-26 01:20:16 INFO Uvicorn running on http://127.0.0.1:6660 (Press CTRL+C to quit)
06-26 01:20:16 [INFO] uvicorn | Started reloader process [4052] using watchgod
2022-06-26 01:20:16 INFO Started reloader process [4052] using watchgod
06-26 01:20:17 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
06-26 01:20:17 [SUCCESS] nonebot | NoneBot is initializing...
06-26 01:20:17 [INFO] nonebot | Current Env: dev
06-26 01:20:17 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 6660, '
log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep':
 {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev'}
06-26 01:20:17 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
06-26 01:20:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
06-26 01:20:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
06-26 01:20:19 [SUCCESS] nonebot | Succeeded to import "modules"
06-26 01:20:20 [SUCCESS] nonebot | Succeeded to import "autosign"
06-26 01:20:20 [SUCCESS] nonebot | Succeeded to import "guess_voice"
06-26 01:20:20 [SUCCESS] nonebot | Succeeded to import "tests"
06-26 01:20:20 [DEBUG] nonebot | Adapter "OneBot V11" already exists
06-26 01:20:20 [SUCCESS] nonebot | Succeeded to import "echo"
06-26 01:20:20 [SUCCESS] nonebot | Succeeded to import "bot"
06-26 01:20:20 [INFO] uvicorn | Started server process [4056]
2022-06-26 01:20:20 INFO Started server process [4056]
06-26 01:20:20 [INFO] uvicorn | Waiting for application startup.
2022-06-26 01:20:20 INFO Waiting for application startup.
06-26 01:20:20 [INFO] nonebot_plugin_gocqhttp | [858036619] 当前版本:v1.0.0-rc3
06-26 01:20:20 [INFO] nonebot_plugin_gocqhttp | [858036619] 将使用 device.json 内的设备信息运行Bot.
06-26 01:20:20 [INFO] nonebot_plugin_gocqhttp | [858036619] 开始尝试登录并同步消息...
06-26 01:20:20 [INFO] nonebot_plugin_gocqhttp | [858036619] 使用协议: iPad
06-26 01:20:20 [INFO] nonebot_plugin_gocqhttp | [858036619] Protocol -> connect to server: [::ffff:14.22.9.53]:8080
06-26 01:20:20 [WARNING] nonebot_plugin_gocqhttp | [858036619] Protocol -> device lock is disable. http api may fail.
06-26 01:20:23 [INFO] nonebot_plugin_gocqhttp | [858036619] 登录成功 欢迎使用: 手撕包菜
06-26 01:20:23 [INFO] nonebot_plugin_gocqhttp | [858036619] 开始加载好友列表...
06-26 01:20:23 [INFO] nonebot_plugin_gocqhttp | [858036619] 共加载 86 个好友.
06-26 01:20:23 [INFO] nonebot_plugin_gocqhttp | [858036619] 开始加载群列表...
06-26 01:20:23 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:6660/go-cqhttp/
06-26 01:20:23 [INFO] nonebot_plugin_apscheduler | Scheduler Started
06-26 01:20:23 [INFO] uvicorn | Application startup complete.
2022-06-26 01:20:23 INFO Application startup complete.
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 共加载 5 个群.
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | go-cqhttp for 858036619 has successfully started.
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 资源初始化完成, 开始处理信息.
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] アトリは、高性能ですから!
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:
6660/onebot/v11/ws
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 正在检查更新.
06-26 01:20:24 [INFO] uvicorn | ('127.0.0.1', 56048) - "WebSocket /onebot/v11/ws" [accepted]
2022-06-26 01:20:24 INFO ('127.0.0.1', 56048) - "WebSocket /onebot/v11/ws" [accepted]
06-26 01:20:24 [INFO] nonebot | OneBot V11 | Bot 858036619 connected
06-26 01:20:24 [INFO] websockets | connection open
2022-06-26 01:20:24 INFO connection open
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:6660/on
ebot/v11/ws
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 检查更新完成. 当前已运行最新版本.
06-26 01:20:24 [INFO] nonebot_plugin_gocqhttp | [858036619] 开始诊断网络情况
06-26 01:20:27 [INFO] nonebot_plugin_gocqhttp | [858036619] 网络诊断完成. 未发现问题
06-26 01:20:33 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: /bh#
(-2006112887)
06-26 01:20:33 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message -2006112887 from 1832399834@[
群:950180960] "/bh#"
06-26 01:20:33 [DEBUG] nonebot | Checking for matchers in priority 1...
06-26 01:20:33 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-26 01:20:33 [INFO] nonebot | Event will be handled by <Matcher from honkai_mys, type=message, priority=1, temp=False>

06-26 01:20:33 [DEBUG] nonebot | Running matcher <Matcher from honkai_mys, type=message, priority=1, temp=False>
06-26 01:20:33 [DEBUG] nonebot | Running handler <Dependent call=<function bh3_player_card at 0x00000064771753A0>, param
s=[ModelField(name='bot', type=Bot, required=True), ModelField(name='ev', type=Event, required=True), ModelField(name='a
rgs', type=Message, required=True)], parameterless=[]>
06-26 01:20:33 [INFO] nonebot | Matcher <Matcher from honkai_mys, type=message, priority=1, temp=False> running complete

06-26 01:20:33 [ERROR] nonebot | Running matcher <Matcher from honkai_mys, type=message, priority=1, temp=False> failed.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\bot\BH\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\honkai_mys\__init__.py", line 76, in bh3_player_card
    region_db = DB("uid.sqlite", tablename="uid_region")
  File ".\honkai_mys\modules\database.py", line 28, in __init__
    super().__init__(
  File "C:\bot\BH\venv\lib\site-packages\sqlitedict.py", line 144, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, .\honkai_mys\modules\../.\honkai_mys\modules\.././data
06-26 01:21:18 [INFO] nonebot_plugin_gocqhttp | [858036619] 收到群 群(950180960) 内 迷失老司机(1832399834) 的消息: /bhf
(-9824993)
06-26 01:21:18 [SUCCESS] nonebot | ONEBOT V11 858036619 | [message.group.normal]: Message -9824993 from 1832399834@[群:9
50180960] "/bhf"
06-26 01:21:18 [DEBUG] nonebot | Checking for matchers in priority 1...
06-26 01:21:18 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match anno
tation PrivateMessageEvent, ignored
06-26 01:21:18 [INFO] nonebot | Event will be handled by <Matcher from honkai_mys, type=message, priority=1, temp=False>

06-26 01:21:18 [DEBUG] nonebot | Running matcher <Matcher from honkai_mys, type=message, priority=1, temp=False>
06-26 01:21:18 [DEBUG] nonebot | Running handler <Dependent call=<function show_finance at 0x00000064771754C0>, params=[
ModelField(name='bot', type=Bot, required=True), ModelField(name='ev', type=Event, required=True), ModelField(name='args
', type=Message, required=True)], parameterless=[]>
06-26 01:21:18 [INFO] nonebot | Matcher <Matcher from honkai_mys, type=message, priority=1, temp=False> running complete

06-26 01:21:18 [ERROR] nonebot | Running matcher <Matcher from honkai_mys, type=message, priority=1, temp=False> failed.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\bot\BH\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\bot\BH\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\BH\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\bot\BH\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\honkai_mys\__init__.py", line 143, in show_finance
    spider = Finance(str(qid))
  File ".\honkai_mys\modules\query.py", line 255, in __init__
    self.db = DB("uid.sqlite", "qid_uid")
  File ".\honkai_mys\modules\database.py", line 28, in __init__
    super().__init__(
  File "C:\bot\BH\venv\lib\site-packages\sqlitedict.py", line 144, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, .\honkai_mys\modules\../.\honkai_mys\modules\.././data

**Comment by chingkingm** [comment]
看起来是找不到data文件夹，你config里的第一项怎么填的

**Comment by Kiana1314** [comment]
![image](https://user-images.githubusercontent.com/107671434/176349744-da3085bd-37ea-42a8-917d-377d65cd538b.png)

**Comment by chingkingm** [comment]
我这边复现不了，定位不到这个错误啊。。
要不试试重新clone吧

**Comment by Kiana1314** [comment]
大佬有没有群或者频道方便交流些

**Comment by Kiana1314** [comment]
谢谢大佬了  我换回hs版了
