### ISSUE TITLE
查询ios服报错一直不出图

### ISSUE THREAD

**Issue by Kiana1314** [chingkingm/honkai_mys#40]
查询ios服报错一直不出图
[2022-07-02 16:24:18,893 nonebot] INFO: Self: 2143298595, Message -1501174317 from 480730750@[群:950180960]: 'bh#3153732
2ios'
2022-07-02 16:24:18 INFO Self: 2143298595, Message -1501174317 from 480730750@[群:950180960]: 'bh#31537322ios'
[2022-07-02 16:24:18,913 崩坏3角色卡片] INFO: Message -1501174317 triggered bh3_player_card.
2022-07-02 16:24:18 INFO Message -1501174317 triggered bh3_player_card.
2022-07-02 16:24:18 INFO opening Sqlite table 'uid_region' in 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\m
odules\\.././data/uid.sqlite'
2022-07-02 16:24:19 INFO opening Sqlite table 'qid_uid' in 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\modu
les\\.././data/uid.sqlite'
2022-07-02 16:24:19 INFO opening Sqlite table 'uid_region' in 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\m
odules\\.././data/uid.sqlite'
2022-07-02 16:24:19 INFO opening Sqlite table 'qid_uid' in 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\modu
les\\.././data/uid.sqlite'
[2022-07-02 16:24:19,851 崩坏3角色卡片] ERROR: <class 'PIL.UnidentifiedImageError'> occured when bh3_player_card handlin
g message -1501174317.
2022-07-02 16:24:19 ERROR <class 'PIL.UnidentifiedImageError'> occured when bh3_player_card handling message -1501174317
.
[2022-07-02 16:24:19,869 崩坏3角色卡片] ERROR: cannot identify image file 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\h
onkai_mys\\modules\\../assets\\AvatarIcon\\9052.png'
Traceback (most recent call last):
  File "C:\bot\HS2\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\__init__.py", line 84, in bh3_player_card
    im = await ind.draw_card(qid)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\modules\image_handle.py", line 408, in draw_card
    bg = await myDraw.avatar(bg, avatar_url=self.index.role.AvatarUrl, qid=qid)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\modules\image_handle.py", line 56, in avatar
    if ImageChops.difference(img_404, Image.open(pic_data)).getbbox() is None:
  File "C:\Program Files\Python38\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\modules\
\../assets\\AvatarIcon\\9052.png'
2022-07-02 16:24:19 ERROR cannot identify image file 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\modules\\.
./assets\\AvatarIcon\\9052.png'
Traceback (most recent call last):
  File "C:\bot\HS2\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\__init__.py", line 84, in bh3_player_card
    im = await ind.draw_card(qid)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\modules\image_handle.py", line 408, in draw_card
    bg = await myDraw.avatar(bg, avatar_url=self.index.role.AvatarUrl, qid=qid)
  File "C:\bot\HS2\HoshinoBot\hoshino\modules\honkai_mys\modules\image_handle.py", line 56, in avatar
    if ImageChops.difference(img_404, Image.open(pic_data)).getbbox() is None:
  File "C:\Program Files\Python38\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\bot\\HS2\\HoshinoBot\\hoshino\\modules\\honkai_mys\\modules\
\../assets\\AvatarIcon\\9052.png'
[2022-07-02 16:24:19,969 nonebot] INFO: Message -1501174317 is ignored: Handled by Hoshino
2022-07-02 16:24:19 INFO Message -1501174317 is ignored: Handled by Hoshino
2022-07-02 16:24:21 INFO received event: meta_event.heartbeat

**Comment by chingkingm** [comment]
9052.png这张图有问题，我这边也有这个错误，在修了
