### ISSUE TITLE
bhf绑定再虚拟环境不可以

### ISSUE THREAD

**Issue by liuzj288** [chingkingm/honkai_mys#50]
09-13 22:36:38 [ERROR] nonebot | Running matcher <Matcher from honkai_mys, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Alex\Documents\LittlePaimon\.\honkai_mys\__init__.py", line 165, in bindcookie
    im = fid.draw()
  File "C:\Users\Alex\Documents\LittlePaimon\.\honkai_mys\modules\image_handle.py", line 939, in draw
    return pic2b64(finance_bg)
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\PIL\Image.py", line 554, in __exit__
    self._fp.close()
  File "C:\Users\Alex\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-wKlBzDCa-py3.9\lib\site-packages\PIL\_util.py", line 19, in __getattr__
    raise self.ex
ValueError: Operation on closed image

**Comment by chingkingm** [comment]
Pillow版本高了，需要在9.2.0以下
